Minirib Rotation and Linediff to clipboard button
hiaselhans/openglider pull request #12
Opened 2024-01-06 20:09 UTC by NikolausKurcz

More accurate Minirib 3D Rotation by Simon
Linediff to clipboard button for lines compare view

2024-01-25 19:03 UTC, hiaselhans requested changes

2024-01-25 19:03 UTC, hiaselhans commented on openglider/gui/views/compare/table/lines_diff.py
> +
Da wird leider die table unbenutzbar.
Ich würde so ca. vorschlagen:

``` python
GliderLineSetTable(QtWidget, CompareView):
    def __init__(...):
        layout = QVBoxLayout()
        self.setLayout(layout)
        layout.addWidget(button)
        self.table_widget = QTable()
        layout.addWidget(self.table_widget)
```

bei update:

`self.table_widget.push_table(...)`

2024-01-25 19:03 UTC, hiaselhans commented on openglider/gui/views/compare/table/lines_diff.py
> +    def copy(self) -> None:
evtl. def copy_to_clipboard(self)

2024-01-25 19:03 UTC, hiaselhans commented on openglider/glider/rib/minirib.py
> +        shape_with_bal = cell.basic_cell.midrib(self.yvalue, True, arc_argument=False).curve.nodes
warum arc_argument=False?

2024-01-29 11:33 UTC, hiaselhans commented on openglider/glider/rib/minirib.py
> +        shape_with_bal = cell.basic_cell.midrib(self.yvalue, True, arc_argument=True).curve.nodes
des wird gar nicht verwendet oder?

2024-01-29 18:37 UTC, NikolausKurcz commented on openglider/glider/rib/minirib.py
> +        shape_with_bal = cell.basic_cell.midrib(self.yvalue, True, arc_argument=True).curve.nodes
der Parameter arc_argument ? 
Soweit ich das durchblicke wird der schon von der midrib finktion verwendet.

2024-02-04 19:18 UTC, merged